Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.hostname = "serasa-test"
 
  config.vm.provider :virtualbox do |v|
  v.name = "serasa-test"
  v.memory = 2048
  v.cpus = 2
 end 
  
###  Install, rebuild and run docker-compose on vagrant up ###

  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", rebuild: true, run: "always"
end