version: "3.5"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: always
    networks:
      - network
    stop_grace_period: 15s

  https-portal:
    container_name: https-portal
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    restart: always
    environment:
      DOMAINS: "localhost -> http://app:8080, serasa.test.local -> http://app:8080"
      STAGE: local
    networks:
      - network
    stop_grace_period: 15s

  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: ./jenkins/Dockerfile
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    links:
      - https-portal
    networks:
      - network
    stop_grace_period: 30s

networks:
  network:

volumes:
  jenkins_home:
