Vagrant.configure("2") do |config|
  
  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.network "forwarded_port", guest: 80, host: 80
    app.vm.network "forwarded_port", guest: 443, host: 443
    app.vm.hostname = "serasa-test-app"
  
    app.vm.provider :virtualbox do |appv|
      appv.name = "serasa-test-app-box"
      appv.memory = 1024
      appv.cpus = 2

    app.vm.provision :docker
    app.vm.provision :docker_compose, yml: "/vagrant/docker/app/docker-compose.yml", rebuild: true, run: "always" 

   end 
  end

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/xenial64"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
    jenkins.vm.network "forwarded_port", guest: 50000, host: 50000
    jenkins.vm.hostname = "serasa-test-jenkins"

    jenkins.vm.provider :virtualbox do |jenkinsv|
      jenkinsv.name = "serasa-test-jenkins-box"
      jenkinsv.memory = 1024
      jenkinsv.cpus = 2

    jenkins.vm.provision :docker
    jenkins.vm.provision :docker_compose, yml: "/vagrant/docker/jenkins/docker-compose.yml", rebuild: true, run: "always" 

   end 
  end
end 
